<?php
if (!defined('ABSPATH')) { exit; }
final class EZEV_Operations_Sync {
    public static function init(): void { add_filter('cron_schedules',[self::class,'schedules']);add_action('ezevo_sync_event',[self::class,'run']); }
    public static function schedules(array $s): array {$s['ezevo_5min']=['interval'=>300,'display'=>'Every 5 minutes'];return $s;}
    public static function schedule(): void { if(!wp_next_scheduled('ezevo_sync_event'))wp_schedule_event(time()+120,'ezevo_5min','ezevo_sync_event'); }
    public static function unschedule(): void { $ts=wp_next_scheduled('ezevo_sync_event');if($ts)wp_unschedule_event($ts,'ezevo_sync_event'); }
    public static function run(): array { $p=EZEV_Operations_Provider_Manager::active();if($p->mode()==='manual')return ['ok'=>true,'message'=>'Manual provider: no remote sync required.'];try{$counts=[];$counts['chargers']=self::sync_chargers($p->fetch_chargers(),$p->key());$counts['connectors']=self::sync_connectors($p->fetch_connectors(),$p->key());$counts['sessions']=self::sync_sessions($p->fetch_sessions(),$p->key());$counts['energy']=self::sync_energy($p->fetch_energy(),$p->key());$counts['alerts']=self::sync_alerts($p->fetch_alerts());EZEV_Operations_DB::log('sync_completed','Provider sync completed.','info',null,$counts);return ['ok'=>true,'counts'=>$counts];}catch(Throwable $e){EZEV_Operations_DB::log('sync_failed',$e->getMessage(),'error');return ['ok'=>false,'message'=>$e->getMessage()];} }
    public static function sync_chargers(array $rows,string $provider): int {global $wpdb;$n=0;$t=EZEV_Operations_DB::table('chargers');foreach($rows as $r){if(empty($r['charger_id'])||empty($r['station_id']))continue;$wpdb->replace($t,['charger_id'=>sanitize_text_field((string)$r['charger_id']),'station_id'=>sanitize_text_field((string)$r['station_id']),'connector_id'=>sanitize_text_field((string)($r['connector_id']??'')),'connector_type'=>sanitize_text_field((string)($r['connector_type']??'CCS2')),'max_power_kw'=>(float)($r['max_power_kw']??0),'status'=>sanitize_key((string)($r['status']??'unknown')),'current_power_kw'=>(float)($r['current_power_kw']??0),'serial_number'=>sanitize_text_field((string)($r['serial_number']??'')),'firmware'=>sanitize_text_field((string)($r['firmware']??'')),'last_seen'=>sanitize_text_field((string)($r['last_seen']??current_time('mysql',true))),'provider'=>$provider,'updated_at'=>current_time('mysql',true)]);$n++;}return $n;}
    public static function sync_connectors(array $rows,string $provider): int {global $wpdb;$n=0;$t=EZEV_Operations_DB::table('connectors');foreach($rows as $r){if(empty($r['connector_id'])||empty($r['charger_id'])||empty($r['station_id']))continue;$wpdb->replace($t,['connector_id'=>sanitize_text_field((string)$r['connector_id']),'charger_id'=>sanitize_text_field((string)$r['charger_id']),'station_id'=>sanitize_text_field((string)$r['station_id']),'connector_type'=>sanitize_text_field((string)($r['connector_type']??'CCS2')),'max_power_kw'=>(float)($r['max_power_kw']??0),'status'=>sanitize_key((string)($r['status']??'available')),'current_power_kw'=>(float)($r['current_power_kw']??0),'last_seen'=>sanitize_text_field((string)($r['last_seen']??current_time('mysql',true))),'provider'=>$provider,'updated_at'=>current_time('mysql',true)]);$n++;}return $n;}
    public static function sync_sessions(array $rows,string $provider): int {global $wpdb;$n=0;$t=EZEV_Operations_DB::table('sessions');foreach($rows as $r){if(empty($r['session_id']))continue;$wpdb->replace($t,['session_id'=>sanitize_text_field((string)$r['session_id']),'station_id'=>sanitize_text_field((string)($r['station_id']??'')),'charger_id'=>sanitize_text_field((string)($r['charger_id']??'')),'connector_id'=>sanitize_text_field((string)($r['connector_id']??'')),'user_ref'=>sanitize_text_field((string)($r['user_ref']??'')),'started_at'=>sanitize_text_field((string)($r['started_at']??current_time('mysql',true))),'ended_at'=>sanitize_text_field((string)($r['ended_at']??''))?:null,'duration_seconds'=>absint($r['duration_seconds']??0),'energy_kwh'=>(float)($r['energy_kwh']??0),'status'=>sanitize_key((string)($r['status']??'completed')),'provider'=>$provider,'provider_payload'=>wp_json_encode($r)]);$n++;}return $n;}
    public static function sync_energy(array $rows,string $provider): int {global $wpdb;$n=0;$t=EZEV_Operations_DB::table('energy');foreach($rows as $r){if(empty($r['station_id']))continue;$wpdb->replace($t,['station_id'=>sanitize_text_field((string)$r['station_id']),'recorded_at'=>sanitize_text_field((string)($r['recorded_at']??current_time('mysql',true))),'grid_kwh'=>(float)($r['grid_kwh']??0),'ev_kwh'=>(float)($r['ev_kwh']??0),'solar_kwh'=>(float)($r['solar_kwh']??0),'bess_charge_kwh'=>(float)($r['bess_charge_kwh']??0),'bess_discharge_kwh'=>(float)($r['bess_discharge_kwh']??0),'peak_kw'=>(float)($r['peak_kw']??0),'provider'=>$provider,'provider_record_id'=>sanitize_text_field((string)($r['provider_record_id']??''))?:null]);$n++;}return $n;}
    public static function sync_alerts(array $rows): int {global $wpdb;$n=0;$t=EZEV_Operations_DB::table('alerts');foreach($rows as $r){if(empty($r['alert_id']))continue;$wpdb->replace($t,['alert_id'=>sanitize_text_field((string)$r['alert_id']),'station_id'=>sanitize_text_field((string)($r['station_id']??'')),'charger_id'=>sanitize_text_field((string)($r['charger_id']??'')),'severity'=>sanitize_key((string)($r['severity']??'medium')),'code'=>sanitize_text_field((string)($r['code']??'')),'title'=>sanitize_text_field((string)($r['title']??'Alert')),'message'=>sanitize_textarea_field((string)($r['message']??'')),'status'=>sanitize_key((string)($r['status']??'open')),'occurred_at'=>sanitize_text_field((string)($r['occurred_at']??current_time('mysql',true))),'acknowledged_at'=>null,'resolved_at'=>null]);$n++;}return $n;}
}
